const userData = [
    {
      companyname: "Company1",
      category: "Technology",
      email: "company1@example.com",
      state: "Punjab",
      location: "Punjab",
      pancard: "ABCDE1234F",
      websitelink: "https://www.company1.com",
      phoneno: "1234567890",
      password: "123456",
     
    },
    {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },

      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },

          {
      companyname: "Company1",
      category: "Technology",
      email: "company1@example.com",
      state: "Punjab",
      location: "Punjab",
      pancard: "ABCDE1234F",
      websitelink: "https://www.company1.com",
      phoneno: "1234567890",
      password: "123456",
     
    },
    {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },

      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },

      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      {
        companyname: "Company1",
        category: "Technology",
        email: "company1@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "ABCDE1234F",
        websitelink: "https://www.company1.com",
        phoneno: "1234567890",
        password: "123456",
       
      },
      
    {
      companyname: "Company2",
      category: "Finance",
      email: "company2@example.com",
      state: "Punjab",
      location: "Punjab",
      pancard: "FGHIJ5678K",
      websitelink: "https://www.company2.com",
      phoneno: "9876543210",
      password: "123456",
   
    },
    {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },    {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },

      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
      {
        companyname: "Company2",
        category: "Finance",
        email: "company2@example.com",
        state: "Punjab",
        location: "Punjab",
        pancard: "FGHIJ5678K",
        websitelink: "https://www.company2.com",
        phoneno: "9876543210",
        password: "123456",
     
      },
  ];
  
  export default userData;
  